export const Items = [
    {
        codigo: 1,
        "Nombre": "Hamburguesa Clasica",
        "Descripcion": "Hamburguesa Clasica con papas fritas y salasa",
        "TipoPorducto": "Comida",
        "Existencia": 11,
        "Precio": 120,
        "Costo": 110,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p6.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 11,
        "impuesto": 18,
        "impuestoValor": 18,
        "ultimo": 12,
        "nombreImagen": "Hamburguesa Clasica",
        "idprincipal": 1,
        "cantidadprincipal": 15,
        "idusuario": 2,
        "movimiento": ""
    },
    {
        codigo: 2,
        "Nombre": "Hamburguesa de Pollo",
        "Descripcion": "Hamburguesa Pollo con papas fritas y salasa",
        "TipoPorducto": "Comida",
        "Existencia": 115,
        "Precio": 110,
        "Costo": 100,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p1.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 16.5,
        "impuestoValor": 16.5,
        "ultimo": 13,
        "nombreImagen": "HamburguesaPollo",
        "idprincipal": 2,
        "cantidadprincipal": 16,
        "idusuario": 3,
        "movimiento": ""
    },
    {
        codigo: 3,
        "Nombre": "Baleada Sencilla",
        "Descripcion": "Baleada Sencilla",
        "TipoPorducto": "Comida",
        "Existencia": 15,
        "Precio": 18,
        "Costo": 15,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p2.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 11,
        "impuesto": 2.25,
        "impuestoValor": 2.25,
        "ultimo": 12,
        "nombreImagen": "BaleadaSencilla",
        "idprincipal": 1,
        "cantidadprincipal": 15,
        "idusuario": 3,
        "movimiento": ""
    },
    {
        codigo: 4,
        "Nombre": "Alitas de Pollo",
        "Descripcion": "Alitas de Pollo Bañadas en Salsa Barbacoa",
        "TipoPorducto": "Comida",
        "Existencia": 15,
        "Precio": 120,
        "Costo": 110,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p3.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 11,
        "impuesto": 18,
        "impuestoValor": 18,
        "ultimo": 12,
        "nombreImagen": "AlitasPollo",
        "idprincipal": 4,
        "cantidadprincipal": 17,
        "idusuario": 1,
        "movimiento": ""
    },
    {
        codigo: 5,
        "Nombre": "Burrito de pollo",
        "Descripcion": "Burrito de Pollo con papas fritas",
        "TipoProducto": "Comida",
        "Existencia": 15,
        "Precio": 110,
        "Costo": 100,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p4.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 16.5,
        "impuestoValor": 16.5,
        "ultimo": 12,
        "nombreImagen": "BurritoPollo",
        "idprincipal": 5,
        "cantidadprincipal": 17,
        "idusuario": 4,
        "movimiento": ""
    },
    {
        codigo: 6,
        "Nombre": "Hot Dog",
        "Descripcion": "Hot Dog",
        "TipoProducto": "Comida",
        "Existencia": 35,
        "Precio": 30,
        "Costo": 25,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p5.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 4.5,
        "impuestoValor": 4.5,
        "ultimo": 12,
        "nombreImagen": "HotDog",
        "idprincipal": 6,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": ""
    },
    {
        codigo: 7,
        "Nombre": "Sandwich",
        "Descripcion": "Sandwich de Jamon y Queso",
        "TipoProducto": "Comida",
        "Existencia": 40,
        "Precio": 60,
        "Costo": 50,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p7.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 9,
        "impuestoValor": 9,
        "ultimo": 12,
        "nombreImagen": "HotDog",
        "idprincipal": 7,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": ""
    },
{
        codigo: 8,
        "Nombre": "Pepsi 1.25",
        "Descripcion": "Pepsi de tamaño mega",
        "TipoProducto": "Bebidas",
        "Existencia": 40,
        "Precio": 35,
        "Costo": 32,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p8.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 5.25,
        "impuestoValor": 5.25,
        "ultimo": 12,
        "nombreImagen": "Pepsi1.25",
        "idprincipal": 8,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": "",
    },
    {
        codigo: 9,
        "Nombre": "Te frio",
        "Descripcion": "Te frio",
        "TipoProducto": "Bebidas",
        "Existencia": 40,
        "Precio": 20,
        "Costo": 18,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p9.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 3,
        "impuestoValor": 3,
        "ultimo": 12,
        "nombreImagen": "TeFrio",
        "idprincipal": 9,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": "",
    },
    {
        codigo: 10,
        "Nombre": "Agua",
        "Descripcion": "Agua",
        "TipoProducto": "Bebidas",
        "Existencia": 40,
        "Precio": 20,
        "Costo": 18,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p10.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 3,
        "impuestoValor": 3,
        "ultimo": 12,
        "nombreImagen": "Agua",
        "idprincipal": 10,
        "cantidadprincipal": 17,
        "idusuario": 7,
        "movimiento": "",
    },
    {
        codigo: 11,
        "Nombre": "Seven Up",
        "Descripcion": "Gaseosa Seven Up",
        "TipoProducto": "Bebidas",
        "Existencia": 40,
        "Precio": 20,
        "Costo": 18,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p10.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 3,
        "impuestoValor": 3,
        "ultimo": 12,
        "nombreImagen": "SevenUp",
        "idprincipal": 11,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": "",
    },
    {
        codigo: 12,
        "Nombre": "Powerade",
        "Descripcion": "Bebida Hidratante",
        "TipoProducto": "Bebidas",
        "Existencia": 40,
        "Precio": 20,
        "Costo": 18,
        "CantidaMinima": 1,
        "exento": 0,
        "Imagen": require('../../assets/images/products/p10.png'),
        "Habilitado": 1,
        "tipo2": "",
        "orden": 12,
        "impuesto": 3,
        "impuestoValor": 3,
        "ultimo": 12,
        "nombreImagen": "SevenUp",
        "idprincipal": 9,
        "cantidadprincipal": 17,
        "idusuario": 6,
        "movimiento": "",
    },
];
